// app/layout.tsx
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ToastProvider from "./components/ToastProvider";


const setInitialTheme = `
(function () {
  try {
    const saved = localStorage.getItem('theme'); // 'light' | 'dark'
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;

    if (saved === 'dark' || (!saved && prefersDark)) {
      document.documentElement.setAttribute('data-theme', 'dark');
    } else {
      document.documentElement.setAttribute('data-theme', 'light');
    }
  } catch (e) {}
})();
`;

const tailwindConfig = `
window.tailwind = { config: { darkMode: 'class', theme: { extend: {} } } };
`;

export const metadata = { title: "News App" };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Load theme instantly before React hydration */}
        <script
          dangerouslySetInnerHTML={{ __html: setInitialTheme }}
        />

        {/* Tailwind CDN config */}
        <script
          dangerouslySetInnerHTML={{ __html: tailwindConfig }}
        />
        <script src="https://cdn.tailwindcss.com"></script>
      </head>

      <body>
        <ThemeProvider
          enableSystem
          defaultTheme="system"
          attribute="class"
        >
          {children}
        </ThemeProvider>
        <ToastProvider/>
      </body>
    </html>
  );
}




// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Poppins } from 'next/font/google';

// const poppins = Poppins({
//   weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
//   style: ['normal', 'italic'],
//   subsets: ['latin'],
//   display: 'swap',
// });




// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const setInitialTheme = `
// (function() {
//   try {
//     const t = localStorage.getItem('theme');
//     if (t) {
//       if (t === 'dark') {
//         document.documentElement.setAttribute('data-theme', 'dark');
//         document.documentElement.classList.add('dark');
//       } else {
//         document.documentElement.setAttribute('data-theme', 'light');
//         document.documentElement.classList.remove('dark');
//       }
//     } else {
//       const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
//       if (prefersDark) {
//         document.documentElement.setAttribute('data-theme', 'dark');
//         document.documentElement.classList.add('dark');
//       } else {
//         document.documentElement.setAttribute('data-theme', 'light');
//         document.documentElement.classList.remove('dark');
//       }
//     }
//   } catch (e) {}
// })();
// `;


// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <script dangerouslySetInnerHTML={{ __html: setInitialTheme }} />
//          <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
//       </head>
//       <body
//         className={poppins.className}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
